In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('diabetes_data.csv')

In [14]:
df

Age   BMI  Blood_Sugar  Diabetes
0    58  25.2          159         1
1    48  24.7          165         0
2    34  23.0          121         0
3    62  18.2          197         1
4    27  21.4          108         0
..  ...   ...          ...       ...
95   34  31.6          168         0
96   64  20.6          119         0
97   20  26.6           82         0
98   44  29.8          129         0
99   26  32.6          126         0

[100 rows x 4 columns]

In [3]:
x = df.iloc[:,0:3].to_numpy()

In [4]:
y = df['Diabetes'].to_numpy()

In [5]:
x

array([[ 58. ,  25.2, 159. ],
       [ 48. ,  24.7, 165. ],
       [ 34. ,  23. , 121. ],
       [ 62. ,  18.2, 197. ],
       [ 27. ,  21.4, 108. ],
       [ 40. ,  30.1, 151. ],
       [ 58. ,  31.4, 173. ],
       [ 38. ,  28.3, 198. ],
       [ 42. ,  33.7,  80. ],
       [ 30. ,  29.1, 111. ],
       [ 30. ,  33.6, 168. ],
       [ 43. ,  32.5,  76. ],
       [ 55. ,  25.6, 159. ],
       [ 59. ,  19.6, 181. ],
       [ 43. ,  24.3, 129. ],
       [ 22. ,  29.4, 182. ],
       [ 41. ,  29.3,  71. ],
       [ 21. ,  28.1, 198. ],
       [ 43. ,  22.7, 117. ],
       [ 63. ,  27.5, 106. ],
       [ 49. ,  24.5,  78. ],
       [ 57. ,  34.5, 168. ],
       [ 21. ,  32.4, 117. ],
       [ 40. ,  30.3, 123. ],
       [ 52. ,  22. , 189. ],
       [ 31. ,  22.4, 185. ],
       [ 41. ,  18.7, 144. ],
       [ 63. ,  30.1, 182. ],
       [ 44. ,  19.9, 173. ],
       [ 68. ,  25.5, 153. ],
       [ 46. ,  21.4, 181. ],
       [ 61. ,  33.2, 168. ],
       [ 47. ,  26.1, 162. ],
       [ 3

In [6]:
y

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

In [8]:
model = LogisticRegression()

In [9]:
model.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred = model.predict(x_test)

In [11]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [12]:
y_test

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [13]:
accuracy_score(y_test,y_pred)

1.0